excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods

type_name:
  min_length: 4 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: iPhone # excluded via string
  allowed_symbols: ["_"] # these are allowed in type names

identifier_name:
  min_length: # only min_length
    warning: 2
    error: 1 # only error
  excluded: # excluded via string array
  allowed_symbols: ["_"]
